CREATE TABLE Workout (
    Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    TypeId INT NOT NULL,
    Distance FLOAT NOT NULL  
);

CREATE TABLE WorkoutTypes(
Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
[Name] NVARCHAR(100) NOT NULL
);